version: '3'

# Define services
services:
  # Postgres Service
  postgres:
    image: 'postgres:alpine'
    restart: always
    environment:
      POSTGRES_USER: playground
      POSTGRES_PASSWORD: playground
      POSTGRES_DB: playground
    ports:
      - "5432:5432"

  # Redis Service
  redis:
    image: 'redis:alpine'
    restart: unless-stopped
    ports:
      - "6379:6379"

# Networks to be created for communication between containers
networks:
  backend:
