export default {
  QUEUE: 'queue',
  UPDATE: 'update',
  ENTITY_LAST_SNAPSHOT: 'last_snapshot-',
  ENTITY_POSITION: 'position-',
  ENTITY_EVENTS: 'events-',
  ENTITY_PATH: 'path-',
  ENTITY_STATE: 'state-',
  ENTITY_ATTACK_TARGET: 'attack_target-',
  ENEMY_ENTITY_TO_ATTACK: 'enemy_to_attack-',
  ENTITY_HEALTH: 'health-',
  ENTITY_EXPERIENCE: 'experience-',
  ENTITY_SKILL: 'skill-',
  PROJECTILE_ROTATION: 'projectile_rotation-',
  PROJECTILE_BOUNDS: 'projectile_bounds-',
  PROJECTILE_POSITION: 'projectile_position-',
  REDIS_PLAYER: 'player-',
};
