export default {
  DOUBLE_SIZE: 8,
  FLOAT_SIZE: 4,
  INT64_SIZE: 8,
  INT32_SIZE: 4,
  INT16_SIZE: 2,
  INT8_SIZE: 1,
  BUFFER_REDUCED_PLAYER_SIZE: 6,
  BUFFER_PLAYER_SIZE: 12,
  BUFFER_REDUCED_ENEMY_SIZE: 6,
  BUFFER_ENEMY_SIZE: 12,
  TIME_TO_TIMEOUT: 10000,
};
